### ISSUE TITLE
How to get the on/off cooking status?

### ISSUE THREAD

**Issue by filmkorn** [dengelke/node-sous-vide#2]
Hallo Daniel!

Would you know if there is any way to tell if the device is running (besides the motor speed)? Could there be some read command for this that I'm not seeing?

Your investigation mentions a STATUS [here](https://github.com/dengelke/node-sous-vide/blob/master/Investigation.md?plain=1#L136) - but I can't spot anything related in the proto definitions.

Any ideas?

**Comment by dengelke** [comment]
Hey @filmkorn 

I think 509.js where the STATUS is from is one of the BLE methods but for the original Anova which doesn't use protobuf for comms (like the nano which I have).

If you have a look [here](https://github.com/dfrankland/sous-vide/blob/master/docs/ble.md) it seems to match the commands in 509.js.

**Comment by dengelke** [comment]
To answer your original question haven't fiddled with the nano for awhile but looking at the motor speed would be the best way of checking if it's running from memory!

**Comment by filmkorn** [comment]
Thank you!
